-- +goose Up
ALTER TABLE filters
    ALTER COLUMN id DROP DEFAULT,
    ALTER COLUMN id TYPE UUID USING gen_random_uuid(),
    ALTER COLUMN id SET DEFAULT gen_random_uuid();

-- +goose Down
-- При откате потеряются данные, потому что UUID → BIGINT не конвертируется обратно.
ALTER TABLE filters
    ALTER COLUMN id DROP DEFAULT,
    ALTER COLUMN id TYPE BIGINT USING 0,
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;