// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package models

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type filterTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *filterTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("filters").
func (v *filterTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *filterTableType) Columns() []string {
	return []string{
		"id",
		"name",
		"query",
		"created_at",
		"updated_at",
	}
}

// NewStruct makes a new struct for that view or table.
func (v *filterTableType) NewStruct() reform.Struct {
	return new(Filter)
}

// NewRecord makes a new record for that table.
func (v *filterTableType) NewRecord() reform.Record {
	return new(Filter)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *filterTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// FilterTable represents filters view or table in SQL database.
var FilterTable = &filterTableType{
	s: parse.StructInfo{
		Type:    "Filter",
		SQLName: "filters",
		Fields: []parse.FieldInfo{
			{Name: "ID", Type: "int64", Column: "id"},
			{Name: "Name", Type: "string", Column: "name"},
			{Name: "Query", Type: "json.RawMessage", Column: "query"},
			{Name: "CreatedAt", Type: "time.Time", Column: "created_at"},
			{Name: "UpdatedAt", Type: "time.Time", Column: "updated_at"},
		},
		PKFieldIndex: 0,
	},
	z: new(Filter).Values(),
}

// String returns a string representation of this struct or record.
func (s Filter) String() string {
	res := make([]string, 5)
	res[0] = "ID: " + reform.Inspect(s.ID, true)
	res[1] = "Name: " + reform.Inspect(s.Name, true)
	res[2] = "Query: " + reform.Inspect(s.Query, true)
	res[3] = "CreatedAt: " + reform.Inspect(s.CreatedAt, true)
	res[4] = "UpdatedAt: " + reform.Inspect(s.UpdatedAt, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *Filter) Values() []interface{} {
	return []interface{}{
		s.ID,
		s.Name,
		s.Query,
		s.CreatedAt,
		s.UpdatedAt,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *Filter) Pointers() []interface{} {
	return []interface{}{
		&s.ID,
		&s.Name,
		&s.Query,
		&s.CreatedAt,
		&s.UpdatedAt,
	}
}

// View returns View object for that struct.
func (s *Filter) View() reform.View {
	return FilterTable
}

// Table returns Table object for that record.
func (s *Filter) Table() reform.Table {
	return FilterTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *Filter) PKValue() interface{} {
	return s.ID
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *Filter) PKPointer() interface{} {
	return &s.ID
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *Filter) HasPK() bool {
	return s.ID != FilterTable.z[FilterTable.s.PKFieldIndex]
}

// SetPK sets record primary key, if possible.
//
// Deprecated: prefer direct field assignment where possible: s.ID = pk.
func (s *Filter) SetPK(pk interface{}) {
	reform.SetPK(s, pk)
}

// check interfaces
var (
	_ reform.View   = FilterTable
	_ reform.Struct = (*Filter)(nil)
	_ reform.Table  = FilterTable
	_ reform.Record = (*Filter)(nil)
	_ fmt.Stringer  = (*Filter)(nil)
)

func init() {
	parse.AssertUpToDate(&FilterTable.s, new(Filter))
}
